api_platform:
    resource: .
    type: api_platform
    prefix: /api/v1


app_swagger_ui:
    path: /api/58179s/documentation
    methods: GET
    defaults: {  _controller: api_platform.swagger.action.ui}

login:
    path: /login
    methods: ['POST']
